// src/theme/colors.ts
export const colorPalettes = {
  dark: {
    background: '#181D23',
    card: '#23272F',
    input: '#23272F',
    inputText: '#fff',
    inputPlaceholder: '#8A8A8A',
    button: '#537D5D',
    buttonText: '#fff',
    buttonDisabled: '#3E5C44',
    text: '#fff',
    textSecondary: '#8A8A8A',
    border: '#23272F',
    error: '#FF4C4C',
    success: '#537D5D',
    warning: '#FFC107',
  },
  light: {
    background: '#F5F5F5',
    card: '#FFFFFF',
    input: '#F0F0F0',
    inputText: '#222',
    inputPlaceholder: '#888',
    button: '#537D5D',
    buttonText: '#fff',
    buttonDisabled: '#BDBDBD',
    text: '#222',
    textSecondary: '#888',
    border: '#E0E0E0',
    error: '#FF4C4C',
    success: '#537D5D',
    warning: '#FFC107',
  },
};
